inventaris/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from adminhome import views as adminhome


urlpatterns = [
    path('admin/', admin.site.urls),
    # LOGIN FROM
    path('', adminhome.index, name='login'),
    path('inventaris/logout', adminhome.logout_view, name='logout'),
    path('register', adminhome.register, name='regis'),
    path('login', adminhome.login_view, name='login_view'),
    # FORGET PASSWORD
    path('changepassword/<int:pk>', adminhome.changepassword, name='changepassword'),
    # ADMIN DASHBOARD
    path('inventaris/', adminhome.dashboard, name='dashboard'),
    # BARANG MASUK
    path('inventaris/barangmasuk',adminhome.barangmasukgrid, name='barangmasuk_grid'),
    path('inventaris/barangmasuk/list',adminhome.barangmasuk, name='barangmasuk_list'),
    path('inventaris/barangmasuk/tambah',adminhome.tambahbarangmasuk, name='barangmasuk_add'),
    path('inventaris/barangmasuk/simpantambah',adminhome.simpantambahbarangmasuk, name='barangmasuk_addcreate'),
    path('inventaris/barangmasuk/edit/<int:pk>', adminhome.editbarangmasuk,name='barangmasuk_edit'),
    path('inventaris/barangmasuk/delete/<int:pk>', adminhome.deletebarangmasuk,name='barangmasuk_delete'),
    path('inventaris/barangmasuk/cari', adminhome.caribarangmasukgrid,name='barangmasuk_grid_cari'),
    path('inventaris/barangmasuk/list/cari', adminhome.caribarangmasuk,name='barangmasuk_cari'),

    # BARANG KELUAR
    path('inventaris/barangkeluar',adminhome.barangkeluargrid, name='barangkeluar_grid'),
    path('inventaris/barangkeluar/list',adminhome.viewbarangkeluar, name='barangkeluar_list'),
    path('inventaris/barangkeluar/tambah',adminhome.addbarangkeluar, name='barangkeluar_add'),
    path('inventaris/barangkeluar/simpantambah',adminhome.simpantambahbarangkeluar, name='barangkeluar_addcreate'),
    path('inventaris/barangkeluar/edit/<int:pk>', adminhome.editbarangkeluar,name='barangkeluar_edit'),
    path('inventaris/barangkeluar/delete/<int:pk>', adminhome.deletebarangkeluar,name='barangkeluar_delete'),
    path('inventaris/barangkeluar/cari', adminhome.caribarangkeluargrid,name='barangkeluar_grid_cari'),
    path('inventaris/barangkeluar/list/cari', adminhome.caribarangkeluar,name='barangkeluar_cari'),

    
    # STOK
    path('inventaris/stok', adminhome.gridstok, name='stok_grid'),
    path('inventaris/stok/cari', adminhome.caristokgrid, name='stok_grid_cari'),
    path('inventaris/stok/list/cari', adminhome.caristoklist, name='stok_cari'),
    path('inventaris/stok/list', adminhome.stok, name='stok_list'),
    
    # LAPORAN
    path('inventaris/laporan/barangmasuk',adminhome.laporanmasuk, name='laporan_masuk'),
    path('inventaris/laporan/barangkeluar',adminhome.laporankeluar, name='laporan_keluar'),
    path('inventaris/laporan/stok', adminhome.laporanstok, name='laporan_stok'),
    path('inventaris/laporan/print/stok', adminhome.print_laporan_stok, name='print_stok'),
    path('inventaris/laporan/print/masuk', adminhome.print_laporan_masuk, name='print_masuk'),
    path('inventaris/laporan/print/keluar', adminhome.print_laporan_keluar, name='print_keluar'),
    
    # USERS
    path('inventaris/users', adminhome.viewuser, name='user'),
    path('inventaris/users/tambah', adminhome.register, name='user_add'),
    path('inventaris/users/edit/<int:pk>', adminhome.edituser, name='user_edit'),
    path('inventaris/users/delete/<int:pk>', adminhome.deleteuser,name='user_delete'),
    path('inventaris/users/cari', adminhome.cariuser,name='user_cari'),
    
    # MASTERDATA
    # MERK
    path('inventaris/masterdata/merk', adminhome.viewmerk, name='merk'),
    path('inventaris/masterdata/merk/tambah',adminhome.addmerk, name='merk_add'),
    path('inventaris/masterdata/merk/edit/<int:pk>', adminhome.editmerk,name='merk_edit'),
    path('inventaris/masterdata/merk/delete/<int:pk>', adminhome.deletemerk,name='merk_delete'),
    path('inventaris/masterdata/merk/cari', adminhome.carimerk,name='merk_cari'),
    
    # JENIS
    path('inventaris/masterdata/jenis', adminhome.viewjenis, name='jenis'),
    path('inventaris/masterdata/jenis/tambah',adminhome.addjenis, name='jenis_add'),
    path('inventaris/masterdata/jenis/edit/<int:pk>', adminhome.editjenis,name='jenis_edit'),
    path('inventaris/masterdata/jenis/delete/<int:pk>', adminhome.deletejenis,name='jenis_delete'),
    path('inventaris/masterdata/jenis/cari', adminhome.carijenis,name='jenis_cari'),
    
    # SUPPLIER 
    path('inventaris/masterdata/supplier', adminhome.viewsupplier, name='supplier'),
    path('inventaris/masterdata/supplier/tambah',adminhome.addsupplier, name='supplier_add'),
    path('inventaris/masterdata/supplier/edit/<int:pk>', adminhome.editsupplier,name='supplier_edit'),
    path('inventaris/masterdata/supplier/delete/<int:pk>', adminhome.deletesupplier,name='supplier_delete'),
    path('inventaris/masterdata/supplier/cari', adminhome.carisuplier,name='supplier_cari'),
    
    # CUSTOMER
    path('inventaris/masterdata/customer', adminhome.viewcustomer, name='customer'),
    path('inventaris/masterdata/customer/tambah',adminhome.addcustomer, name='customer_add'),
    path('inventaris/masterdata/customer/edit/<int:pk>', adminhome.editcustomer,name='customer_edit'),
    path('inventaris/masterdata/customer/delete/<int:pk>', adminhome.deletecustomer,name='customer_delete'),
    path('inventaris/masterdata/customer/cari', adminhome.caricustomer,name='customer_cari'),
    
    # TIPE
    path('inventaris/masterdata/tipe', adminhome.viewtipe, name='tipe'),
    path('inventaris/masterdata/tipe/tambah',adminhome.addtipe, name='tipe_add'),
    path('inventaris/masterdata/tipe/edit/<int:pk>', adminhome.edittipe,name='tipe_edit'),
    path('inventaris/masterdata/tipe/delete/<int:pk>', adminhome.deletetipe,name='tipe_delete'),
    path('inventaris/masterdata/tipe/cari', adminhome.caritipe,name='tipe_cari'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminhome/models.py
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.db import models

# Create your models here.

class Jenis_brg(models.Model):
    """docstring for jenis"""
    id_jenis = models.AutoField(primary_key=True)
    nama_jenis = models.CharField(max_length=100,unique=True)
    is_deleted = models.CharField(max_length=100,blank=True , null=True)

    class Meta:
        db_table = "tb_jenis_brg"

    def __str__(self):
        return self.nama_jenis

class Supplier(models.Model):
    id_supplier = models.AutoField(primary_key=True)
    nama_supplier = models.CharField(max_length=100,unique=True)
    alamat_supplier = models.CharField(max_length=100)
    notlp_supplier = models.CharField(max_length=100,unique=True)
    is_deleted = models.CharField(max_length=100,blank=True , null=True)
    class Meta:
        db_table = "tb_supplier"
    
    def __str__(self):
        return self.nama_supplier

class Customer(models.Model):
    id_customer = models.AutoField(primary_key=True)
    nama_customer = models.CharField(max_length=100,unique=True)
    alamat_customer = models.CharField(max_length=100)
    notlp_customer= models.CharField(max_length=100)
    is_deleted = models.CharField(max_length=100,blank=True , null=True)
    class Meta:
        db_table = "tb_customer"
    
    def __str__(self):
        return self.nama_customer

class Merk_brg(models.Model):
    """docstring for merk"""
    id_merk = models.AutoField(primary_key=True)
    nama_merk = models.CharField(max_length=100,unique=True)
    is_deleted = models.CharField(max_length=100,blank=True , null=True)
    class Meta:
        db_table = "tb_merk_brg"
    
    def __str__(self):
        return self.nama_merk

class Tipe_brg(models.Model):
    """docstring for jenis"""
    id_tipe = models.AutoField(primary_key=True)
    nama_tipe = models.CharField(max_length=100,unique=True)
    is_deleted = models.CharField(max_length=100,blank=True , null=True)
    class Meta:
        db_table = "tb_tipe_brg"
    
    def __str__(self):
        return self.nama_tipe

class Barang_masuk(models.Model):
    """docstring for barang_masuk"""
    id_brg_masuk = models.AutoField(primary_key=True)
    kd_barang = models.CharField(max_length=10)
    nm_barang = models.CharField(max_length=100)
    tgl_masuk = models.DateField()
    jml_masuk = models.IntegerField()
    harga_satuan = models.IntegerField()
    no_resi = models.CharField(max_length=100,blank=True)
    foto_masuk = models.ImageField(upload_to='foto/',blank=True , null=True) 
    is_deleted = models.CharField(max_length=100,blank=True , null=True)

    supplier_id = models.ForeignKey(Supplier,on_delete=models.SET_NULL, null=True,db_column='supplier_id')
    jenis_id = models.ForeignKey(Jenis_brg,on_delete=models.SET_NULL, null=True,db_column='jenis_id')
    merk_id = models.ForeignKey(Merk_brg,on_delete=models.SET_NULL, null=True,db_column='merk_id')
    tipe_id = models.ForeignKey(Tipe_brg,on_delete=models.SET_NULL, null=True,db_column='tipe_id')
    

    class Meta:
        db_table = "tb_barang_masuk"
    
    def __str__(self):
        return self.nm_barang

    def delete(self, *args, **kwargs):
        self.foto_masuk.delete()
        super().delete(*args, **kwargs)


class Barangkeluar(models.Model):
    """docstring for barang_keluar"""
    id = models.AutoField(primary_key=True)
    nama_barang = models.CharField(max_length=100)
    tanggal = models.DateField()
    serialnumber = models.CharField(max_length=20)
    kode_barang = models.CharField(max_length=10)
    no_bukti = models.CharField(max_length=20)
    no_resi = models.CharField(max_length=20,blank=True)
    jumlah = models.IntegerField()
    harga_satuan = models.IntegerField()
    total_bayar = models.IntegerField()

    jenis_id = models.ForeignKey(Jenis_brg,on_delete=models.CASCADE,db_column='jenis_id')
    merk_id = models.ForeignKey(Merk_brg,on_delete=models.CASCADE,db_column='merk_id')
    tipe_id = models.ForeignKey(Tipe_brg,on_delete=models.CASCADE,db_column='tipe_id')
    
    alamat_customer = models.CharField(max_length=100)
    customer_id =  models.ForeignKey(Customer,on_delete=models.CASCADE,db_column='customer_id')
    foto_keluar = models.ImageField(upload_to='foto/', blank=True, null=True)
    is_deleted = models.CharField(max_length=100,blank=True , null=True)

    class Meta:
        db_table = "tb_barang_keluar"

    def __str__(self):
        return self.nama_barang

    # agar file yang diupload bisa dihapus dr folder
    def delete(self, *args, **kwargs):
        self.foto_keluar.delete()
        super().delete(*args, **kwargs)

class Stok_barang(models.Model):
    id_stok = models.AutoField(primary_key=True)
    tanggal = models.DateField()
    nm_barang= models.CharField(max_length=100)
    kd_barang = models.CharField(max_length=100)
    hrg_barang = models.IntegerField()
    jumlah_stok = models.IntegerField(default=0)
    stok_akhir = models.IntegerField(default=0)
    keterangan = models.CharField(max_length=100)
    foto_stok = models.ImageField(upload_to='foto/',blank=True , null=True)

    jenis_id = models.ForeignKey(Jenis_brg, on_delete=models.SET_NULL, null=True,db_column='jenis_id')
    merk_id = models.ForeignKey(Merk_brg, on_delete=models.SET_NULL, null=True,db_column='merk_id')
    tipe_id = models.ForeignKey(Tipe_brg, on_delete=models.SET_NULL, null=True,db_column='tipe_id')

    class Meta:
        db_table = "tb_stok"
    
    def __str__(self):
        return self.kd_barang

    def delete(self, *args, **kwargs):
        self.foto_stok.delete()
        super().delete(*args, **kwargs)

class Akun(models.Model):
    """docstring for user"""
    USER_CHOICES = [
        ('Admin', 'Admin'),
        ('SuperAdmin', 'SuperAdmin'),
    ]
    
    nm_lengkap = models.CharField(max_length=255)
    level = models.CharField(max_length=20, choices=USER_CHOICES, default='SuperAdmin')
    is_deleted = models.CharField(max_length=10,blank=True , null=True,default=False)

    akun = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.nm_lengkap

    class Meta:
        db_table = "tb_user"

adminhome/templates/changepassword.html
{% extends  "layout/admin/base-admin.html" %}

{% load static %}

{% block extrastyle %}
<link rel="stylesheet" href="/static/assets/bootstrap/css/bootstrap-select.css">
{% endblock%}

{% block page_content %}

<section class="content-header">
    <!-- Horizontal Form -->
    <div class="box box-warning col-md-12">
        <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-edit"></i> Ubah Password <b> - {{ request.session.nm_lengkap }}</b></h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <div class="col-md-9 col-xs-9 col-lg-9">        
            <form class="form-horizontal" action="{% url 'changepassword' pk=user.pk %}" method="POST">
                {% csrf_token %}
                <div class="box-body">
                    <div class="form-group">
                        <label for="first_name" class="col-sm-2 control-label">{{form.first_name.label}}: </label>
                        <div class="col-sm-10">
                            {{form.first_name}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="first_name" class="col-sm-2 control-label">{{form.last_name.label}}: </label>
                        <div class="col-sm-10">
                            {{form.last_name}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="first_name" class="col-sm-2 control-label">{{form.username.label}}: </label>
                        <div class="col-sm-10">
                            {{form.username}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="first_name" class="col-sm-2 control-label">{{form.email.label}}: </label>
                        <div class="col-sm-10">
                            {{form.email}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="first_name" class="col-sm-2 control-label">{{form.password.label}}: </label>
                        <div class="col-sm-10">
                            {{form.password}}
                        </div>
                    </div>
                    <!-- <div class="col-md-offset-3 col-xs-offset-3 col-lg-offset-3"> -->
                        <div class="form-group pull-right">
                            <button type="button" class="btn btn-warning"  data-toggle="modal" data-target="#myModal">Edit</button>
                            <!-- modal konfirmasi delete -->
                            <div class="modal fade" id="myModal" style="display: none;">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">×</span></button>
                                                <h4 class="modal-title">Konfirmasi Ubah Password</h4>
                                            </div>
                                            <div class="modal-body">
                                                <p>Apakah anda yakin ingin mengubah password anda ?</p>
                                            </div>
                                            <div class="modal-footer">
                                                <input type="submit" value="Edit" class="btn btn-warning"></input>
                                                <button type="button" class="btn btn-primary" data-dismiss="modal">Tidak</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <a href="{% url 'dashboard' %}" type="button" class="btn btn-primary">Kembali</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
        {% endblock %}
        {% block extrajs%}
        <script src="/static/assets/bootstrap/js/bootstrap-select.js"></script>
        <script>
            $('#datepicker').datepicker({
                autoclose: true
            });
            $('#id_first_name,#id_last_name,#id_email,#id_username').attr('readonly',true);
            // $('#id_level').prop('disabled',true);
        </script>
        {% endblock %}

adminhome/templates/dashboard.html
{% extends  "layout/admin/base-admin.html" %}

{% load static %}

{% block page_content %}

<section class="content-header">
    <h2 style="text-align: center; text-transform: uppercase;">SELAMAT DATANG, {{request.session.first_name}} !</h2>
    <h3 style=" margin-left: 70px; margin-right: 70px; text-align: justify">
        Sistem Informasi Inventaris Barang merupakan sebuah sistem 
        untuk mempermudah dalam memberikan informasi dan laporan 
        mengenai barang masuk dan barang keluar pada perusahaan 
        CV. Adisatya IT Consultant.
    </h3>
    <br/>
    <br/>
    <br/>
    <div class="row col-12" style=" margin-left: 70px; margin-right: 70px">
        <div class="box box-danger col-sm-4">
            <h4>Jumlah Stok Barang Kurang Dari 10:</h4>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Kode barang</th>
                        <th>Nama Barang</th>
                        <th>Jumlah Stok</th>
                    </tr>
                </thead>
                <tbody>
                    {% if daftar_stok %}
                    {% for stok in daftar_stok %}
                    {% if stok.stok_akhir < 10  %}
                    <tr>
                        <td>{{ stok.kd_barang }}</td>
                        <td>{{ stok.nm_barang }}</td>
                        <td>
                            {{ stok.stok_akhir }} Unit
                        </td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</section>
{% endblock %}

adminhome/templates/login.html
{% include "layout/base.html" %}

{% load static %}

{% block content %}
<section class="login-form">
    <form method="POST" action="/login" role="login">
        {% csrf_token %}
        {% if messages %}
        <div class="alert alert-danger">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </div>
        {% endif %}
        <strong><h6><center>SISTEM INFORMASI INVENTARIS BARANG</center></h6></strong>
        <img src="{% static 'assets/images/logo.png' %}" class="img-responsive" width="100" height="100" />
        <center><h5>CV. Adisatya IT Consultant</h5></center>
        <input type="text" name="login_username" placeholder="Username" required class="form-control input-lg" />
        <input type="password" name="login_password" placeholder="Password" required class="form-control input-lg" />
        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Sign In" />
    </form>
</section>
{% endblock %}